manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ggrocer
      url-base: https://github.com/greengrocer98
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 9ebbeff0a8b69a42f14aec022cdf16c7a107b9e0
      import: app/west.yml
    - name: zmk-paw3395-driver
      remote: ggrocer
      revision: 586803f02441b7d84f12f077a2fca540b3e9d9d5
    - name: zmk-vfx-rgbled-indicator
      remote: ggrocer
      revision: 402d781adbd9e5b4f5318c50bb2763e3c3f28790
    - name: zmk-input-processor-report-rate-limit
      remote: badjeff
      revision: b056cb135525933743e2627150fb390f9d4b2461
  self:
    path: config
